[package]
name = "injection"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain", features = ["implement"] }
infra = { path = "../infra" }
controller = { path = "../controller", features = ["implement"] }
importer = { path = "../importer" }
util = { path = "../util" }
