[package]
name = "injection"
version = "0.1.0"
edition = "2021"

[dependencies]
usecase = { path = "../usecase" }
infra = { path = "../infra" }
controller = { path = "../controller" }
util = { path = "../util" }