//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod dao;
pub mod entity;
pub mod import;
pub mod migration;
pub mod repository;
pub mod config;

pub(crate) const DATABASE_URL: &str = "sqlite:./data/database.db?mode=rwc";
