//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod config;
pub mod dao;
pub mod entity;
pub mod migration;
pub mod repository;

pub(crate) const DATABASE_URL: &str = "sqlite:./data/database.db?mode=rwc";
