//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "zone")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::wwn::Entity")]
    Wwn,
}

impl Related<super::wwn::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wwn.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
