[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
usecase = { path = "../usecase" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
axum = { version = "0.7.5", features = ["macros"] }