[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
util = { path = "../util" }

[features]
implement = []
